repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you wish to point at
    hooks:
    -   id: trailing-whitespace  # Removes trailing whitespace at the end of lines
    -   id: end-of-file-fixer  # Ensures files end with a newline
    -   id: check-added-large-files  # Prevents adding large files to the repo


-   repo: https://github.com/psf/black
    rev: 23.10.0  # Use the version you wish
    hooks:
    -   id: black  # Formats Python code to the black coding style

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the version you wish
    hooks:
    -   id: isort  # Sorts Python imports

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the version you wish
    hooks:
    -   id: flake8
