apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoally-imadapter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autoally-imadapter
  template:
    metadata:
      labels:
        app: autoally-imadapter
    spec:
      containers:
        - name: autoally-imadapter
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: slack-secret
          env:
            - name: ROOT_PATH
              value: "/imadapter"
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-harbor-secret
