apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
type: Opaque
data:
  SLACK_SIGNING_SECRET: {{ .Values.slackSigningSecret | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slackBotToken | b64enc | quote }}
