replicaCount: 1

image:
  repository: fullstackjam/autoally-backend
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8000

resources: {}

slackSigningSecret: f0b96064610645f398236a186e28a0f7
slackBotToken: xoxb-4877290900210-6060854467301-hTc9zjBvNc6aCvpIx5x98slx
