apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "autoally-backend.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "autoally-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autoally-backend.commonLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          env:
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: SLACK_SIGNING_SECRET
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: SLACK_BOT_TOKEN
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
