apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoally-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autoally-backend
  template:
    metadata:
      labels:
        app: autoally-backend
    spec:
      containers:
        - name: autoally-backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: slack-secret
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
