apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoally-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autoally-backend
  template:
    metadata:
      labels:
        app: autoally-backend
    spec:
      containers:
      - name: autoally-backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: my-autoally-backend-secret
              key: SLACK_SIGNING_SECRET
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-autoally-backend-secret
              key: SLACK_BOT_TOKEN
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
