apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "autoally-backend.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "autoally-backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
