name: Deploy to Kubernetes

on:
  push:
    branches:
      - master # Adjust this to your main branch if it's not "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Kubernetes config
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $GITHUB_WORKSPACE/kubeconfig

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.6.0' # Set your desired Helm version

    - name: Deploy with Helm
      run: |
        helm upgrade --install imadapter-release helm/autoally-imadapter --atomic --kubeconfig $GITHUB_WORKSPACE/kubeconfig
