name: Docker Build and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t imadapter-test:latest .

    - name: Run the Docker container
      run: docker run -d -p 8000:8000 imadapter-test:latest

    - name: Test the application inside Docker
      run: |
        sleep 10  # give the application some time to start
        curl http://127.0.0.1:8000/
