name: Deploy Helm Chart

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.13.1'

      - name: Calculate New Version
        id: newversion
        run: |
          INCREMENTED_NUMBER=$(git rev-list --count HEAD)
          COMMIT_HASH=$(git rev-parse --short=7 HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          NEW_VERSION="${INCREMENTED_NUMBER}-${COMMIT_HASH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update Image Tag in values.yaml
        run: |
          sed -i "s/tag: .*/tag: \"${{ env.NEW_VERSION }}\"/" helm/autoally-imadapter/values.yaml

      - name: Package Helm Chart
        id: package_chart
        run: |
          CHART_PATH=$(helm package helm/autoally-imadapter | grep -o 'Successfully packaged chart and saved it to: .*' | awk '{print $NF}')
          echo "CHART_PATH=$CHART_PATH" >> $GITHUB_ENV

      - name: Login to Harbor
        run: helm registry login harbor.fullstackjam.dev --username ${{ secrets.HARBOR_USERNAME }} --password ${{ secrets.HARBOR_PASSWORD }}
        env:
          HELM_EXPERIMENTAL_OCI: 1

      - name: Push Chart to Harbor
        run: helm push ${{ env.CHART_PATH }} oci://harbor.fullstackjam.dev/fullstackjam

      - name: Logout of Harbor
        run: helm registry logout harbor.fullstackjam.dev
