name: Deploy Helm Chart

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
            version: '3.13.1'

      - name: Package Helm Chart
        run: helm package helm/autoally-imadapter

      - name: Login to Harbor
        run: helm registry login harbor.fullstackjam.com --username ${{ secrets.HARBOR_USERNAME }} --password ${{ secrets.HARBOR_PASSWORD }}
        env:
            HELM_EXPERIMENTAL_OCI: 1

      - name: Push Chart to Harbor
        run: helm push autoally-imadapter-0.1.0.tgz oci://harbor.fullstackjam.com/fullstackjam

      - name: Logout of Harbor
        run: helm registry logout harbor.fullstackjam.com
